renv::install(c(
    "mlr-org/mlr3", 
    "mlr-org/bbotk", 
    "mlr-org/mlr3tuning", 
    "mlr-org/mlr3pipelines@feat/inner_valid", 
    "mlr-org/paradox", 
    "mlr-org/mlr3learners", 
    "mlr-org/mlr3extralearners@inner_valid", 
    "mlr-org/mlr3mbo@randombot_ncar"))
